### ISSUE TITLE
Concerns about knee points detection

### ISSUE THREAD

**Issue by xiangx7805** [CNFeffery/DataScienceStudyNotes#1]
Hi CNFeffery,

Thanks for sharing the knee points detection idea and the paper!

I have 2questions:

1. I've reproduced the whole process using the latest data (to Feb 23), and I found that the detection machine gives a different result in late Feb. With the latest data, the plot shows that there's a convex increasing on Feb 22, instead of the concave decreasing on Feb 18. Is that a bad sign?

2. Why do you set `online = False` when creating the `knee_point_search`  function?

It would be greatly appreciated if you can help me with the questions!

**Comment by CNFeffery** [comment]
Hi @xiangx7805,

Thanks for reading my article and reproduced it!

For question 1, `kneed` only return the best result( globally optimal result), so the result may change in latest data. 

For question 2, as I mentioned in the article, set `online = False`, `kneed` will detect knee point from right to left until  it find first knee point, I think people care about the latest knee point, so I set this parameter to `False`.
