### ISSUE TITLE
geopandas 里的中国地图没有藏南

### ISSUE THREAD

**Issue by smartlixx** [CNFeffery/DataScienceStudyNotes#2]
非常感谢你的分享。在讲 geopandas 坐标系时，中国地图（geopandas 自带，natural earth 的数据）缺少藏南。Cartopy 也是用的同样地图。建议不要使用 geopandas 自带的地图，改用 shapefile，像你的其它博文里用的那样。

![China_map_problems](https://user-images.githubusercontent.com/16891009/79416335-fc91bc80-7fe1-11ea-9d8c-6238d1614cf8.jpg)

**Comment by CNFeffery** [comment]
@smartlixx 谢谢你的提醒，我之后涉及中国地图都会使用其他的完整的矢量数据:cry:
