### ISSUE TITLE
二维kdeplot()如何获取核密度值z及其所在位置坐标，以及不同颜色阴影的坐标？

### ISSUE THREAD

**Issue by dickwxyz** [CNFeffery/DataScienceStudyNotes#3]

**Comment by CNFeffery** [comment]
@dickwxyz 你可以参考下面的方式取出绘制二维核密度图使用到的数据研究研究，看看是不是你所需要的结果：
![image](https://user-images.githubusercontent.com/49147660/84014487-f948fa80-a9ac-11ea-99d5-38881f84c911.png)

**Comment by dickwxyz** [comment]
是的，但是z值木有找到相关的属性🤣

**Comment by CNFeffery** [comment]
> 是的，但是z值木有找到相关的属性🤣

z轴没有，因为这个图是分层了的，你可以用scipy自己算出来，seaborn本身也是调用的scipy

**Comment by dickwxyz** [comment]
> > 是的，但是z值木有找到相关的属性🤣
> 
> z轴没有，因为这个图是分层了的，你可以用scipy自己算出来，seaborn本身也是调用的scipy

研究了源码，有两种计算kde的方法，默认是statsmodels.nonparametric.api.smnp()，另一种方法是
stats.gaussian_kde()。
下面是源码
```
import statsmodels.nonparametric.api as smnp
from six import string_types

bw="scott"
gridsize=100
cut=3
clip=None

if isinstance(bw, string_types):
    bw_func = getattr(smnp.bandwidths, "bw_" + bw)
    x_bw = bw_func(x)
    y_bw = bw_func(y)
    bw = [x_bw, y_bw]
elif np.isscalar(bw):
    bw = [bw, bw]

# Determine the clipping
if clip is None:
    clip = [(-np.inf, np.inf), (-np.inf, np.inf)]
elif np.ndim(clip) == 1:
    clip = [clip, clip]

def _kde_support(data, bw, gridsize, cut, clip):
    """Establish support for a kernel density estimate."""
    support_min = max(data.min() - bw * cut, clip[0])
    support_max = min(data.max() + bw * cut, clip[1])
    return np.linspace(support_min, support_max, gridsize)

x = Y.T[0]
y = Y.T[1]
kde = smnp.KDEMultivariate([x, y], "cc", bw)
x_support = _kde_support(x, kde.bw[0], gridsize, cut, clip[0])
y_support = _kde_support(y, kde.bw[1], gridsize, cut, clip[1])
xx, yy = np.meshgrid(x_support, y_support)
z = kde.pdf([xx.ravel(), yy.ravel()]).reshape(xx.shape)
```

**Comment by CNFeffery** [comment]
> > > 是的，但是z值木有找到相关的属性🤣
> > 
> > 
> > z轴没有，因为这个图是分层了的，你可以用scipy自己算出来，seaborn本身也是调用的scipy
> 
> 研究了源码，有两种计算kde的方法，默认是statsmodels.nonparametric.api.smnp()，另一种方法是
> stats.gaussian_kde()。
> 下面是源码
> 
> ```
> import statsmodels.nonparametric.api as smnp
> from six import string_types
> 
> bw="scott"
> gridsize=100
> cut=3
> clip=None
> 
> if isinstance(bw, string_types):
>     bw_func = getattr(smnp.bandwidths, "bw_" + bw)
>     x_bw = bw_func(x)
>     y_bw = bw_func(y)
>     bw = [x_bw, y_bw]
> elif np.isscalar(bw):
>     bw = [bw, bw]
> 
> # Determine the clipping
> if clip is None:
>     clip = [(-np.inf, np.inf), (-np.inf, np.inf)]
> elif np.ndim(clip) == 1:
>     clip = [clip, clip]
> 
> def _kde_support(data, bw, gridsize, cut, clip):
>     """Establish support for a kernel density estimate."""
>     support_min = max(data.min() - bw * cut, clip[0])
>     support_max = min(data.max() + bw * cut, clip[1])
>     return np.linspace(support_min, support_max, gridsize)
> 
> x = Y.T[0]
> y = Y.T[1]
> kde = smnp.KDEMultivariate([x, y], "cc", bw)
> x_support = _kde_support(x, kde.bw[0], gridsize, cut, clip[0])
> y_support = _kde_support(y, kde.bw[1], gridsize, cut, clip[1])
> xx, yy = np.meshgrid(x_support, y_support)
> z = kde.pdf([xx.ravel(), yy.ravel()]).reshape(xx.shape)
> ```

嗯嗯，我记成scipy了，你可以按照这样自己计算
