### ISSUE TITLE
'https://overpass.kumi.systems/api/interpreter'这个网址里面没有数据

### ISSUE THREAD

**Issue by winynfuck** [CNFeffery/DataScienceStudyNotes#4]
您好作者，我调试了这个程序，发现无法下载路网数据，错误原因可能是https://overpass.kumi.systems/api/interpreter这个网站无法爬到数据，会提示如下信息：
The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.

Error: encoding error: Your input contains only whitespace.
请问您之前在调试程序的时候是否也出现过这个问题呢？

**Comment by CNFeffery** [comment]
> 您好作者，我调试了这个程序，发现无法下载路网数据，错误原因可能是[https://overpass.kumi.systems/api/interpreter这个网站无法爬到数据，会提示如下信息：](https://overpass.kumi.systems/api/interpreter%E8%BF%99%E4%B8%AA%E7%BD%91%E7%AB%99%E6%97%A0%E6%B3%95%E7%88%AC%E5%88%B0%E6%95%B0%E6%8D%AE%EF%BC%8C%E4%BC%9A%E6%8F%90%E7%A4%BA%E5%A6%82%E4%B8%8B%E4%BF%A1%E6%81%AF%EF%BC%9A)
> The data included in this document is from [www.openstreetmap.org](http://www.openstreetmap.org). The data is made available under ODbL.
> 
> Error: encoding error: Your input contains only whitespace.
> 请问您之前在调试程序的时候是否也出现过这个问题呢？

那篇文章是蛮早以前写的了，我也不再继续维护那个程序了，推荐你用osmnx这个库来下载osm路网，很方便

**Comment by winynfuck** [comment]
好嘞，我去了解一下，谢谢您，祝好！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月29日(星期四) 下午4:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [CNFeffery/DataScienceStudyNotes] &#39;https://overpass.kumi.systems/api/interpreter&#39;这个网址里面没有数据 (#4)





  
您好作者，我调试了这个程序，发现无法下载路网数据，错误原因可能是https://overpass.kumi.systems/api/interpreter这个网站无法爬到数据，会提示如下信息：
 The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.
 
Error: encoding error: Your input contains only whitespace.
 请问您之前在调试程序的时候是否也出现过这个问题呢？
  
那篇文章是蛮早以前写的了，我也不再继续维护那个程序了，推荐你用osmnx这个库来下载osm路网，很方便
